[build]
  publish = "public"
  command = "echo $CYPRESS_CACHE_FOLDER && ls -la ./node_modules/.cache"
  functions = "./functions/"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
